name: Local Docker Build and Run
on:
  push:
    branches: [ master ]  # or your working branch

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run with Docker Compose
        run: |
          docker-compose down --volumes
          docker-compose build
          docker-compose up -d
